### ISSUE TITLE
Abstracting away errors

### ISSUE THREAD

**Issue by oldergod** [square/whorlwind#30]
The 3 operations: `canStoreSecurely`, `write`, and `read` are executed in wild environments.
How about allowing callbacks to be passed to each that would be executed if anything gets thrown?

Basically, this

```java
boolean canStoreSecurely();
void write(String name, ByteString value);
Observable<ReadResult> read(String name);
```
would become
```java
interface OnErrorListener {
  void onError(Throwable t);
}

boolean canStoreSecurely(@Nullable OnErrorListener onErrorListener);
void write(String name, ByteString value, @Nullable OnErrorListener onErrorListener);
Observable<ReadResult> read(String name, @Nullable OnErrorListener onErrorListener);
```

**Comment by mattprecious** [comment]
I think I'd prefer this passed into the factory/constructor instead of at each callsite?

**Comment by JakeWharton** [comment]
What's the goal here? How does this change the behavior of Observable and Completable?

**Comment by mattprecious** [comment]
We're trying to remove our stupid class that composes `Whorlwind`, which eats all the errors from crappy devices and logs to bugsnag instead of crashing. Want to make that behavior optional..

**Comment by JakeWharton** [comment]
Ah, right. I remember that thing. Second question still stands.

**Comment by oldergod** [comment]
- If an error callback *is not* set ⇒ throw the error down the stream
- if an error callback *is* set ⇒ `.doOnError(callback).onErrorResumeNext(/* something */)`

**Comment by mattprecious** [comment]
Yeah, the behavior change is to attach error handling everywhere so you don't need to worry about it at every call site... Not that important for `read()` since it's a stream and those are easy to attach error handling to. It was important for `write` before we changed that to a `Completable`, so I guess it's not that important there anymore. `canStoreSecurely()` is still a pain to have to try/catch it. @oldergod and I are looking through our reports now to see if we can handle those ones differently and then maybe this error handling can just be turned into extension functions internal to the app.

**Comment by oldergod** [comment]
Let's say we don't need that for now
